[2024-03-22T06:22:44.993+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fetch_articles_workflow.transform manual__2024-03-22T06:22:25.192202+00:00 [queued]>
[2024-03-22T06:22:45.036+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fetch_articles_workflow.transform manual__2024-03-22T06:22:25.192202+00:00 [queued]>
[2024-03-22T06:22:45.037+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-03-22T06:22:45.062+0000] {taskinstance.py:2217} INFO - Executing <Task(_PythonDecoratedOperator): transform> on 2024-03-22 06:22:25.192202+00:00
[2024-03-22T06:22:45.083+0000] {standard_task_runner.py:60} INFO - Started process 1038 to run task
[2024-03-22T06:22:45.092+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'fetch_articles_workflow', 'transform', 'manual__2024-03-22T06:22:25.192202+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/fetch_articles.py', '--cfg-path', '/tmp/tmptfq_yj2f']
[2024-03-22T06:22:45.100+0000] {standard_task_runner.py:88} INFO - Job 10: Subtask transform
[2024-03-22T06:22:45.403+0000] {task_command.py:423} INFO - Running <TaskInstance: fetch_articles_workflow.transform manual__2024-03-22T06:22:25.192202+00:00 [running]> on host 1b79855aa23a
[2024-03-22T06:22:45.992+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='mitchomzz@gmail.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='fetch_articles_workflow' AIRFLOW_CTX_TASK_ID='transform' AIRFLOW_CTX_EXECUTION_DATE='2024-03-22T06:22:25.192202+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-03-22T06:22:25.192202+00:00'
[2024-03-22T06:22:46.000+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/fetch_articles.py", line 42, in transform
    from transformation import transform_data
ImportError: cannot import name 'transform_data' from 'transformation' (/opt/airflow/dags/transformation.py)
[2024-03-22T06:22:46.092+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=fetch_articles_workflow, task_id=transform, execution_date=20240322T062225, start_date=20240322T062244, end_date=20240322T062246
[2024-03-22T06:22:46.163+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 10 for task transform (cannot import name 'transform_data' from 'transformation' (/opt/airflow/dags/transformation.py); 1038)
[2024-03-22T06:22:46.198+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-03-22T06:22:46.301+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
